---
  version: '2'
  services:
    centos6:
      image: deadc/docker-ansible-centos6
      ulimits:
        nofile:
          soft: 65536
          hard: 65536
      cap_add:
        - SYS_ADMIN
      security_opt:
        - seccomp:unconfined
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
        - .:/ansible/roles/test
      privileged: true
      extra_hosts:
        - "localhost.localdomain:127.0.0.1"

    centos7:
      image: deadc/docker-ansible-centos7
      ulimits:
        nofile:
          soft: 65536
          hard: 65536
      cap_add:
        - SYS_ADMIN
      security_opt:
        - seccomp:unconfined
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
        - .:/ansible/roles/test
      privileged: true

    debian9:
      image: deadc/docker-ansible-debian9
      ulimits:
        nofile:
          soft: 65536
          hard: 65536
      cap_add:
        - SYS_ADMIN
      security_opt:
        - seccomp:unconfined
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
        - .:/ansible/roles/test
      privileged: true

    amazon1:
      image: deadc/docker-ansible-amazon1
      ulimits:
        nofile:
          soft: 65536
          hard: 65536
      cap_add:
        - SYS_ADMIN
      security_opt:
        - seccomp:unconfined
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
        - .:/ansible/roles/test
      privileged: true
      extra_hosts:
        - "localhost.localdomain:127.0.0.1"
